name: Compile TS and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    name: Compile TS and run tests - Node.js ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: npm run test

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

      - name: Automated Version Bump
        if: github.ref == 'refs/heads/main'
        uses: phips28/gh-action-bump-version@v9.0.13
        with:
          minor-wording:  'add,Adds,new,Added'
          major-wording:  'MAJOR,cut-major,breaking-change'
          patch-wording:  'patch,fixes,Fixed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

